import { createApp } from 'vue'
import '@m3e/web/theme'
import '@m3e/web/nav-rail'
import '@m3e/web/icon'
import '@m3e/web/icon-button'
import '@m3e/web/button'
import '@m3e/web/search'
import '@m3e/web/content-pane'
import '@m3e/web/chips'
import '@m3e/web/list'
import '@m3e/web/divider'
import '@m3e/web/shape'
import '@m3e/web/checkbox'
import '@m3e/web/progress-indicator'
import '@m3e/web/heading'
import '@m3e/web/form-field'
import '@m3e/web/switch'
import App from './App.vue'
import './style.css'

createApp(App).mount('#app')
